from __future__ import annotations

import json
import os
import shutil
import tempfile
from pathlib import Path
from typing import Any

from .models import DailyEntry, now_iso


DATA_DIRS = [
    Path("data/daily"),
    Path("data/weekly"),
    Path("data/monthly"),
    Path("data/inbox"),
    Path("data/drafts"),
    Path("logs"),
    Path("templates"),
]


TEMPLATE_CONTENTS = {
    "night_review_prompt.md": """# 夜の振り返り
## 今日のMain
- 完了
- 一部進んだ
- 未着手
## 最低ライン
- 達成
- 未達
## 今日できたこと
## 崩れた原因
## 明日変えることを1つだけ
## 日記（任意）
""",
    "tomorrow_plan_prompt.md": """# 明日の指示書

* Mainは最大3つ
* 優先順位は院試、研究、筋トレ・健康、競馬AI、定期収入、松尾研、読書
* 予定を詰め込みすぎない
* 通常タスクは目安6件以内
* 各タスクに最低ラインを付ける
* 明日変えることは1つだけ
* ユーザー承認前は提案版として扱う
""",
    "weekly_review_prompt.md": """# 週次振り返り

* 今週の勝ち
* Mainの成績
* 最低ライン達成率
* 崩れた原因ランキング
* 未承認の提案版
* 来週変えること1つ
""",
    "chatgpt_night_output_prompt.md": """# ChatGPT夜入力用プロンプト

ユーザーの夜の振り返りを、以下のJSON形式だけで出力してください。

- Markdownコードブロックは使わない
- JSON以外の説明文は付けない
- raw_logはユーザーの元文章を改変せず保存する
- Mainは最大3つ
- 各タスクに最低ラインを付ける
- 通常タスクは原則6件以内
- 明日変えることは1つだけ
- 提案版は未承認状態
- target_dateは振り返り日の翌日
- 優先順位は院試、研究、筋トレ・健康、競馬AI、定期収入、松尾研、読書
- 当日の確定版タスクIDが分かる場合だけtask_resultsを入れる
- CLIのtoday --show-idsまたは確定版に表示されたタスクIDだけを使う
- 存在しないIDを推測で作らない
- タスクIDが不明な場合はtask_resultsを空配列にする
- task_resultsのstatusはcompleted、partial、minimum_only、not_started、skippedだけを使う
- minimum_line_achievedはtrueまたはfalseにする
- close-dayへ渡す1つのJSONだけを出力する

```json
{
  "date": "YYYY-MM-DD",
  "raw_log": "ユーザーの元文章を改変せずに入れる",
  "diary": "日記として残す短い文章",
  "task_results": [
    {
      "task_id": "task-1",
      "status": "completed",
      "note": "大問1を最後まで解いた",
      "minimum_line_achieved": true
    }
  ],
  "structured_review": {
    "today_main": [
      {
        "area": "院試",
        "status": "一部進んだ",
        "note": "過去問の問題文を確認した"
      }
    ],
    "minimum_line": {
      "院試": "達成",
      "研究": "未達"
    },
    "what_went_well": [
      "学校に行けた"
    ],
    "breakdown_causes": [
      "スマホ"
    ],
    "one_change_tomorrow": "朝イチで過去問を開く"
  },
  "tomorrow_plan_proposal": {
    "target_date": "YYYY-MM-DD",
    "main": [
      "院試",
      "研究",
      "筋トレ・健康"
    ],
    "tasks": [
      {
        "area": "院試",
        "task": "過去問を大問1つ解く",
        "priority": 1,
        "minimum_line": "問題文を開く"
      }
    ],
    "one_change_tomorrow": "朝イチで過去問を開く"
  }
}

```
""",
}


# These are the repository-managed prompts needed for ordinary operation.
# The ChatGPT output prompt is generated by init when absent, but is optional
# for workspaces that use their own input format.
REQUIRED_TEMPLATE_NAMES = (
    "night_review_prompt.md",
    "tomorrow_plan_prompt.md",
    "weekly_review_prompt.md",
)


def resolve_root(root: Path | None = None) -> Path:
    """Resolve the data root without changing an explicitly supplied path."""
    if root is not None:
        return root.expanduser().resolve()

    current = Path.cwd().resolve()

    def is_project_root(path: Path) -> bool:
        return (path / "pyproject.toml").is_file() and (path / "src" / "daily_review").is_dir()

    if is_project_root(current):
        return current
    child_project = current / "daily-review"
    if is_project_root(child_project):
        return child_project
    for parent in current.parents:
        if is_project_root(parent):
            return parent
    return current


def init_workspace(root: Path) -> tuple[list[Path], list[Path]]:
    created: list[Path] = []
    existing: list[Path] = []
    for relative in DATA_DIRS:
        path = root / relative
        if path.exists():
            existing.append(path)
        else:
            path.mkdir(parents=True, exist_ok=True)
            created.append(path)

    templates_dir = root / "templates"
    for name, content in TEMPLATE_CONTENTS.items():
        path = templates_dir / name
        if path.exists():
            existing.append(path)
        else:
            path.write_text(content, encoding="utf-8")
            created.append(path)
    return created, existing


def daily_path(root: Path, day: str) -> Path:
    return root / "data" / "daily" / f"{day}.json"


def daily_log_path(root: Path, day: str) -> Path:
    return root / "logs" / f"{day}.md"


def weekly_path(root: Path, start: str, end: str) -> Path:
    return root / "data" / "weekly" / f"{start}_{end}.json"


def weekly_log_path(root: Path, start: str, end: str) -> Path:
    return root / "logs" / f"weekly_{start}_{end}.md"


def monthly_path(root: Path, month: str) -> Path:
    return root / "data" / "monthly" / f"{month}.json"


def monthly_log_path(root: Path, month: str) -> Path:
    return root / "logs" / f"monthly_{month}.md"


def inbox_path(root: Path, day: str) -> Path:
    return root / "data" / "inbox" / f"{day}.json"


def draft_path(root: Path, day: str) -> Path:
    return root / "data" / "drafts" / f"{day}.json"


def read_json_file(path: Path) -> dict[str, Any]:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        raise ValueError(
            f"JSONの読み込みに失敗しました: {path} の {exc.lineno}行{exc.colno}列付近（{exc.msg}）"
        ) from exc


def load_daily(root: Path, day: str) -> dict[str, Any] | None:
    path = daily_path(root, day)
    if not path.exists():
        return None
    return read_json_file(path)


def new_daily(day: str) -> dict[str, Any]:
    timestamp = now_iso()
    return {
        "date": day,
        "created_at": timestamp,
        "updated_at": timestamp,
    }


def load_or_create_daily(root: Path, day: str) -> dict[str, Any]:
    return load_daily(root, day) or new_daily(day)


def atomic_write_json(path: Path, payload: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    DailyEntry.model_validate(payload)
    serialized = json.dumps(payload, ensure_ascii=False, indent=2, sort_keys=False)
    fd, tmp_name = tempfile.mkstemp(
        prefix=f".{path.name}.",
        suffix=".tmp",
        dir=str(path.parent),
        text=True,
    )
    tmp_path = Path(tmp_name)
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as handle:
            handle.write(serialized)
            handle.write("\n")
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(tmp_path, path)
    finally:
        if tmp_path.exists():
            tmp_path.unlink()


def atomic_write_json_data(path: Path, payload: dict[str, Any]) -> None:
    """Atomically write a non-daily JSON document without applying DailyEntry validation."""
    path.parent.mkdir(parents=True, exist_ok=True)
    serialized = json.dumps(payload, ensure_ascii=False, indent=2, sort_keys=False)
    fd, tmp_name = tempfile.mkstemp(
        prefix=f".{path.name}.",
        suffix=".tmp",
        dir=str(path.parent),
        text=True,
    )
    tmp_path = Path(tmp_name)
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as handle:
            handle.write(serialized)
            handle.write("\n")
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(tmp_path, path)
    finally:
        if tmp_path.exists():
            tmp_path.unlink()


def atomic_write_json_many(writes: list[tuple[Path, dict[str, Any]]]) -> list[Path]:
    prepared: list[tuple[Path, Path, bool, Path | None]] = []
    replaced: list[tuple[Path, bool, Path | None]] = []
    try:
        for path, payload in writes:
            path.parent.mkdir(parents=True, exist_ok=True)
            DailyEntry.model_validate(payload)
            serialized = json.dumps(payload, ensure_ascii=False, indent=2, sort_keys=False)
            fd, tmp_name = tempfile.mkstemp(
                prefix=f".{path.name}.",
                suffix=".tmp",
                dir=str(path.parent),
                text=True,
            )
            tmp_path = Path(tmp_name)
            with os.fdopen(fd, "w", encoding="utf-8") as handle:
                handle.write(serialized)
                handle.write("\n")
                handle.flush()
                os.fsync(handle.fileno())
            backup_path: Path | None = None
            if path.exists():
                backup_fd, backup_name = tempfile.mkstemp(
                    prefix=f".{path.name}.",
                    suffix=".bak",
                    dir=str(path.parent),
                )
                os.close(backup_fd)
                backup_path = Path(backup_name)
                shutil.copy2(path, backup_path)
            prepared.append((path, tmp_path, path.exists(), backup_path))

        for path, tmp_path, existed, backup_path in prepared:
            os.replace(tmp_path, path)
            replaced.append((path, existed, backup_path))
    except Exception:
        for path, existed, backup_path in reversed(replaced):
            if existed and backup_path and backup_path.exists():
                os.replace(backup_path, path)
            elif not existed and path.exists():
                path.unlink()
        raise
    finally:
        for _, tmp_path, _, backup_path in prepared:
            if tmp_path.exists():
                tmp_path.unlink()
            if backup_path and backup_path.exists():
                backup_path.unlink()
    return [path for path, _ in writes]


def save_daily(root: Path, day: str, payload: dict[str, Any]) -> Path:
    payload["date"] = day
    payload["updated_at"] = now_iso()
    payload.setdefault("created_at", payload["updated_at"])
    path = daily_path(root, day)
    atomic_write_json(path, payload)
    return path


def write_text(path: Path, content: str) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return path
